# File di inventario per Ansible
#
# Sostituisci "your_server_ip" con l'indirizzo IP del tuo server di destinazione.
# Assicurati di avere accesso SSH tramite chiave pubblica.

[webservers]
_REPLACE_WITH_YOUR_SERVER_IP_ ansible_user=root
